import { LEGAL } from './legal.js'

export default {
  nav: {
    links: [
      { id: 'offre', label: 'What we do' },
      { id: 'realisations', label: 'Projects' },
      { id: 'process', label: 'How it works' },
      { id: 'faq', label: 'FAQ' },
    ],
    cta: 'Contact us',
  },
  hero: {
    pre: 'Focus on your business,',
    grad: 'we automate',
    post: 'the rest',
    sub: 'Re-typing data, chasing reminders, endless Excel sheets: we take care of it, with tools built around the way you work.',
    ctaPrimary: "Let's talk about your needs",
    ctaRealisations: 'See our projects',
    ctaProcess: 'How it works',
    note: 'Free, no-commitment first call · Based in Lyon, France',
  },
  problem: {
    title: 'Sound familiar?',
    intro: 'Situations we see in almost every small business.',
    items: [
      { icon: 'repeat', title: 'The same data typed twice', desc: 'An order comes in by email, you copy it into your invoicing software, then into an Excel sheet.' },
      { icon: 'sheet', title: 'The Excel file that runs everything', desc: 'A spreadsheet patched together over the years that only one person really knows how to use.' },
      { icon: 'bell', title: 'Chasing everything by hand', desc: 'Pending quotes, unpaid invoices, appointment reminders: it all relies on your memory.' },
      { icon: 'puzzle', title: "Software that doesn't fit", desc: 'You pay a subscription for a tool you have to work around every single day.' },
    ],
    foot: "Those hours can be won back. That's what we do.",
  },
  offer: {
    title: 'What we do',
    intro: 'We start from the way you work, not from an off-the-shelf solution.',
    blocks: [
      {
        tag: 'Connect your tools',
        title: 'Your software finally talks to each other',
        desc: 'We connect your tools (email, invoicing, CRM, spreadsheets…) so information flows on its own.',
        example: 'E.g. an order received by email shows up directly in your invoicing tool.',
      },
      {
        tag: 'Automate',
        title: 'Repetitive tasks run on their own',
        desc: 'Reminders, reports, exports, filing: we automate what takes up your time every week without giving anything back.',
        example: 'E.g. your monthly report ready on the 1st, without touching it.',
      },
      {
        tag: 'Bespoke',
        title: 'A tool built for your business',
        desc: 'When nothing on the market fits, we build the app or internal tool that matches the way you work.',
        example: 'E.g. a site-tracking tool that replaces three Excel files.',
      },
      {
        tag: 'Useful AI',
        title: 'AI, only when it helps',
        desc: "Sorting emails, drafting a quote, summarising a document: we use it when it truly saves time, and we tell you when it doesn't.",
        example: 'E.g. incoming email requests sorted and sent to the right person.',
      },
    ],
    cta: { text: 'Recognise one of these needs?', button: "Let's talk" },
  },
  realisations: {
    title: "What we've already built",
    intro: 'Real projects, for real businesses.',
    link: 'See the project',
    cta: { text: 'A need like one of these projects?', button: "Let's talk" },
  },
  process: {
    title: 'How it works',
    intro: 'No surprises, from the first call to delivery.',
    steps: [
      { n: '01', name: 'We talk', desc: '30 minutes, free and with no commitment. We tell you honestly whether we can help.' },
      { n: '02', name: 'We scope', badge: 'paid step', desc: 'We define exactly what to build and at what price. You get a clear quote.' },
      { n: '03', name: 'We build', desc: 'With regular check-ins so you can follow the progress.' },
      { n: '04', name: 'We deliver and stay around', desc: 'Tool delivered, explained to your team, and we stay available as it evolves.' },
    ],
    cta: { text: 'Ready to start?', button: 'Book a free call' },
  },
  about: {
    title: 'Who we are',
    lead: 'No agency. You talk directly to the person who builds your tool.',
    paragraphs: [
      'myblok is Baptiste, a developer based in Lyon. Day to day, he works as a work-study developer at Crédit Agricole T&S, on systems where "roughly right" does not exist. He brings the same rigour to your projects.',
    ],
    points: [
      { k: 'Direct contact', v: 'No salesperson, no middleman.' },
      { k: 'Fair price', v: "Without a big firm's markup." },
      { k: 'On site or remote', v: 'We come to you when needed, otherwise everything is handled remotely.' },
    ],
  },
  faq: {
    title: 'Questions we often get',
    items: [
      { q: 'How much does it cost?', a: 'It depends on the need, which is why we start with a free call. After scoping, you get a precise quote: you know exactly what you pay before we start.' },
      { q: 'How long does it take?', a: 'A simple automation can be up and running in a few days; a custom tool usually takes a few weeks. The exact timeline is set during scoping.' },
      { q: "I'm not technical at all. Is that a problem?", a: 'No, that is the case for most of our clients. You explain how you work, we handle the rest, and we explain the tool in plain words.' },
      { q: 'Do we need to change our current software?', a: 'Usually not. We start from what you already use and make it work better. We only suggest replacing a tool when it is genuinely simpler for you.' },
      { q: 'What if something stops working after delivery?', a: 'We stay reachable. Fixes related to our work are covered, and we can agree on follow-up if your tool needs to evolve.' },
      { q: 'Is our data safe?', a: 'We only access what the project needs, and your data stays with you or in the tools you chose. If you prefer solutions hosted in Europe, we take that into account from scoping.' },
      { q: 'Do you use AI?', a: 'When it is useful, yes. But most time savings come from simple automations, without AI. We pick the best-suited tool, not the trendiest one.' },
    ],
  },
  contact: {
    title: "Let's talk about your needs",
    subtitle: 'Describe your situation in two lines. We reply within 48 hours.',
    name: 'Your name',
    company: 'Your company',
    optional: 'optional',
    email: 'Your email',
    emailPlaceholder: 'you@company.com',
    message: 'Your need in a few words',
    messagePlaceholder: 'E.g. we re-enter our orders in two different software tools…',
    submit: 'Send',
    sending: 'Sending…',
    success: "Message sent. We'll get back to you very soon.",
    error: 'Sending failed. Just email us directly at the address below.',
    or: 'or directly',
    privacy: 'Your information is used only to reply to you. Never sold, never used for marketing.',
    privacyLink: 'Privacy policy',
  },
  footer: {
    tagline: 'Custom tools that save SMEs time.',
    location: 'Lyon, France',
    contactLink: 'Contact',
    legalLink: 'Legal notice',
    privacyLink: 'Privacy policy',
    owner: 'sole trader',
  },
  legal: {
    title: 'Legal notice',
    lines: [
      ['Publisher', `myblok — ${LEGAL.name}, sole trader (auto-entrepreneur, France)`],
      ['SIREN', LEGAL.siren],
      ['Registered address', LEGAL.address],
      ['Publication director', LEGAL.name],
      ['Contact', LEGAL.email],
      ['Host', 'Vercel Inc. — 340 S Lemon Ave #4133, Walnut, CA 91789, USA — vercel.com'],
    ],
    privacy: {
      title: 'Privacy policy',
      intro:
        'The contact form is the only place on this site where we ask you for personal information. Here is exactly what happens to it.',
      lines: [
        ['Data collected', 'Your name, your email address, your company name if you provide it, and the content of your message. Nothing else: no data gathered without your knowledge.'],
        ['Purpose', 'Answering your enquiry and, if it turns into a project, preparing a proposal. No unsolicited marketing, no resale, no list shared with anyone.'],
        ['Legal basis', 'Your own request: steps taken at your request prior to entering into a contract (Article 6(1)(b) GDPR).'],
        ['Recipients', `Baptiste, and no one else. The email is delivered through our sending provider ${LEGAL.mailProvider}, covered by a data processing agreement and the European Commission’s standard contractual clauses.`],
        ['Hosting', 'The site and the form are hosted by Vercel Inc. (USA), under the same contractual framework.'],
        ['Retention', 'Three years from our last exchange, then deletion. If an engagement starts, the related data is kept for the duration of the work and the accounting and legal obligations that follow.'],
        ['Cookies and analytics', 'No cookies. We measure site traffic with Vercel Web Analytics, anonymously and in aggregate: no cookies, no personal identification, no tracking across sites. No advertising, no social widgets. Only your theme choice is stored in your browser: it never leaves your device and requires no consent.'],
        ['Your rights', `Access, rectification, erasure, restriction, objection and portability. An email to ${LEGAL.email} is enough, we answer within one month.`],
      ],
    },
  },
  theme: { toDark: 'Switch to dark mode', toLight: 'Switch to light mode' },
  meta: {
    home: {
      title: 'myblok — Automation and custom tools for SMEs | Lyon',
      description: 'Win back hours every week: we automate your repetitive tasks and build the tools your business is missing. Direct, from Lyon.',
    },
    legal: { title: 'Legal notice — myblok', description: 'Legal notice for myblok.fr.' },
    privacy: {
      title: 'Privacy policy — myblok',
      description: 'What myblok does with the information sent through the contact form, and your rights.',
    },
    notFound: { title: 'Page not found — myblok', description: 'This page does not exist.' },
  },
  notFound: {
    title: 'This page does not exist.',
    text: 'The link may be old or mistyped.',
    back: 'Back to the home page',
  },
  realisation: {
    back: 'All our projects',
    context: 'The context',
    problem: 'The problem',
    solution: 'What we did',
    result: 'The result',
    duration: 'Project length',
    cta: { text: 'A need that looks like this one?', button: "Let's talk" },
  },
}
